{...
#!/usr/bin/ruby
#encoding: UTF-8

...}


{...


class Code
  
  include Enumerable
  
  def initialize(parts)
    @parts = parts
  end
  
  def self.from x
    case x
    when Code then x
    when String then Code.new([x])
    else raise %(can not convert #{x.inspect} to #{Code})
    end
  end
  
  def + other
    Code.new(self.parts + Code.from(other).parts)
  end
  
  protected
  
  # Private.
  attr_reader :parts
  
end


# returns empty Code.
def code
  Code.new([])
end


...}
